const SUMMARY_LABEL_WIDTH = 18;
const STATUS_LABEL_WIDTH = 16;
const PATH_LABEL_WIDTH = 64;
const FIELD_GAP = "     ";
const INFO_LABEL_WIDTH = 18;
const DEFAULT_THREADS = 4;
const DEFAULT_BIGFILE_MB = 1;
const DEFAULT_TOTALSIZE_MB = 5;
const DEFAULT_FILECOUNT_THRESHOLD = 30;

module.exports = {
  SUMMARY_LABEL_WIDTH,
  STATUS_LABEL_WIDTH,
  PATH_LABEL_WIDTH,
  FIELD_GAP,
  INFO_LABEL_WIDTH,
  DEFAULT_THREADS,
  DEFAULT_BIGFILE_MB,
  DEFAULT_TOTALSIZE_MB,
  DEFAULT_FILECOUNT_THRESHOLD,
};
