const SUMMARY_LABEL_WIDTH = 17;
const STATUS_LABEL_WIDTH = 12;
const PATH_LABEL_WIDTH = 64;
const FIELD_GAP = "     ";
const INFO_LABEL_WIDTH = 18;

module.exports = {
  SUMMARY_LABEL_WIDTH,
  STATUS_LABEL_WIDTH,
  PATH_LABEL_WIDTH,
  FIELD_GAP,
  INFO_LABEL_WIDTH,
};
